# URL de conexión (Usando el puerto 6543 para el Pooler de Supabase)
spring.datasource.url=postgresql://postgres.mgihbjhgpvylzlqmjdup:${SUPA_DB}@aws-1-us-east-1.pooler.supabase.com:6543/postgres



spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.mgihbjhgpvylzlqmjdup
spring.datasource.password=${SUPA_DB}

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
