# URL de conexión (Usando el puerto 6543 para el Pooler de Supabase)
spring.datasource.url=jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:6543/postgres?prepareThreshold=0

# Usuario (Copia el usuario largo que aparece en tu imagen)
spring.datasource.username=postgres.wzlqnyidditqopwyxboh

# Contraseña (La que tú definiste al crear el proyecto en Supabase)
spring.datasource.password=${SUPA_DB}

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración adicional recomendada para Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update